services:
  db:
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: "test"
      MARIADB_PASSWORD: "test"
      MARIADB_DATABASE: "test"
      MARIADB_ROOT_PASSWORD: "admin"
  phpmyadmin:
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
