name: Docker Image build, push, deploy

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to registery
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REG_URL }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REG_URL }}/nezu-mail:latest
      - name: Deploy
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WATCHTOWER_URL }}/v1/update
          method: 'GET'
          bearerToken: ${{ secrets.WATCHTOWER_TOKEN }}
          preventFailureOnNoResponse: 'true'
